In [7]:
import numpy as np
arr=np.array([1,2,3])
new_arr=np.append(arr,4)
print(arr)
print(new_arr)

[1 2 3]
[1 2 3 4]


In [2]:
#Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều:
arr = np.array([1, 2, 3, 4, 5])
new_element = 10
index_to_insert = 2
new_arr = np.insert(arr, index_to_insert, new_element)
print(new_arr)

[ 1  2 10  3  4  5]


In [3]:
#Thêm phần tử vào vị trí cụ thể trong mảng 2 chiều:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
new_element = [7, 8]
row_to_insert = 1
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0)
print(new_arr_2d)

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


In [9]:
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều:
arr = np.array([1, 2, 3, 4, 5])
imdices = np.where(arr=3)
indices

TypeError: where() got an unexpected keyword argument 'arr'

In [6]:
arr = np.array([1, 2, 3, 4, 5])
imdices = np.argwhere(arr=3)
indices

TypeError: argwhere() got an unexpected keyword argument 'arr'

In [ ]:
arr = np.array([1, 5, 2, 3, 4])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print(max_idx)
print(min_idx)