In [6]:
import numpy as np
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều:
arr = np.array([1, 2, 3, 4, 5])
imdices = np.where(arr==3)
imdices

(array([2]),)

In [9]:
arr = np.array([1, 5, 2, 3, 4])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print(max_idx)
print(min_idx)

1
0


In [10]:
#Sắp xếp tăng
arr = np.array([1, 2, 3, 4, 5])
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

In [12]:
arr = np.array([1, 2, 3, 4, 5])
arr.sort()
arr

array([1, 2, 3, 4, 5])

In [11]:
#Sắp xếp giảm:
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]
sorted_arr_descending

array([5, 4, 3, 2, 1])

In [ ]:
#Sử dụng phương thức sort() của mảng và đảo ngược mảng
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]
sorted_arr_descending