In [16]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Số chiều của mảng là:",arr.ndim)
print("Kích thước của mảng là:",arr.shape)
print("Tổng số phần tử trong mảng là:", arr.shape)
print("Kiểu dữ liệu của các phần tử trong mảng là:", arr.dtype)
print("Kích thước theo (byte) của mỗi phần tử trong mảng là:", arr.itemsize)
print("Tổng kích thước theo (byte) của mảng là: ", arr.nbytes)

Số chiều của mảng là: 2
Kích thước của mảng là: (2, 3)
Tổng số phần tử trong mảng là: (2, 3)
Kiểu dữ liệu của các phần tử trong mảng là: int64
Kích thước theo (byte) của mỗi phần tử trong mảng là: 8
Tổng kích thước theo (byte) của mảng là:  48


In [9]:
import numpy as np
arr_a = np.array([[1,2,3,4],
[5,6,7,8],
[9,10,11,12]])
#dùng hàm np.sum() và không có 'axis'
np.sum(arr_a)


array([15, 18, 21, 24])

In [ ]:
#Dùng hàm np.sum() với 'axis =0'
np.sum(arr_a,axis=0)

In [8]:
#Dùng hàm np.sum với 'axis=1'
np.sum(arr_a, axis=1)

array([10, 26, 42])

In [18]:
import numpy as np
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B[1,2]
B[0,0] 
B[2,0] 
B[2,-1] 
B[0,0]=0 #Chỉnh sửa giá trị ở dòng 0, cột 0 thành 0
np.array(B)

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
import numpy as np
A=np.arange(10)
A


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
A[:5]

array([0, 1, 2, 3, 4])

In [37]:
A[4:7] #Các hần tử ở vị trí thứ thứ năm đến thứ 7

array([4, 5, 6])

In [39]:
 A[5:] #Các phần tử ở sau vị trí 5.

array([5, 6, 7, 8, 9])

In [40]:
import numpy as np
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
B

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [41]:
B[:2,:3] # Hai dòng, ba cột

array([[1, 2, 3],
       [5, 6, 7]])

In [42]:
B[ ::-1, ::-1] #Lấy các hàng từ hàng cuối lên bước nhảy là -1
 #Lấy các cột từ bên phải sang, bước nhảy là -1

array([[2, 1, 0, 9],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [43]:
B[:3,::2] #Lấy các hàng từ bắt đầu từ 0 đến hàng 3 (không bao gồm hàng này)
 #Lấy các cột với bước nhảy là 2 bắt đầu từ cột 0

array([[1, 3],
       [5, 7],
       [9, 1]])

In [2]:
import numpy as np
# Tạo mảng 2 chiều 3x3
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Lấy view mới chỉ chứa 2 dòng và 2 cột của mảng gốc
arr_view = arr_2d[:2, :2].view()
print(arr_view) #in mảng con arr_con vừa được slicing từ hàm view

[[1 2]
 [4 5]]


In [4]:
# Thay đổi giá trị trong view
arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 10.
print(arr_view)

[[100   2]
 [  4   5]]


In [5]:
print("Mảng gốc sau khi thay đổi giá trị trong view:")
print(arr_2d) #in ra mảng arr ban đầu. 

Mảng gốc sau khi thay đổi giá trị trong view:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [9]:
sub_arr_copy=arr_2d[:2,:2] #slicing mảng con lấy 2 dòng, 2 cột của mảng arr
print(sub_arr_copy) #in mảng con arr_con vừa được slicing

[[100   2]
 [  4   5]]


In [10]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) #tạo ma trận hàng thông qua reshape.

array([[1, 2, 3]])

In [11]:
x[np.newaxis, :] #Tạo ma trận hàng thông qua newaxis

array([[1, 2, 3]])

In [12]:
x.reshape((3, 1)) #Tạo ma trận cột thông reshape

array([[1],
       [2],
       [3]])

In [13]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y]) #Kết hợp ma trận x, y

array([1, 2, 3, 4, 5, 6])