In [5]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y]) #Kết hợp ma trận x, y

array([1, 2, 3, 4, 5, 6])

In [7]:
import numpy as np
a = np.array([[1, 2],
 [3, 4]])
b = np.array([[5, 6],
 [7, 8]])
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng
c = np.concatenate((a, b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
# Kết hợp theo chiều thứ hai (trục ngang/trục 1) của mảng, trục được đánh chỉ số từ 0.
d = np.concatenate([a, b], axis=1)
print(d)

[[1 2 5 6]
 [3 4 7 8]]


In [12]:
import numpy as np
a = np.array([[1, 2],
              [3,4]])
b = np.array([[5, 6],
              [7, 8]])
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng
c = np.vstack((a, b))
# Kết hợp theo chiều ngang (trục ngang/ trục 1) của mảng
d = np.hstack((a,b))
print(c)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [13]:
import numpy as np
arr = np.arange(10) #Tạo mảng arr gồm 10 phần tử từ 0-9
sub_arr1=np.split(arr,[3, 6]) #chia mảng arr theo chỉ mục [3, 6]
#Phần đầu tiên bắt đầu từ chỉ mục 0 và kết thúc trước chỉ mục 3.
#Phần thứ hai bắt đầu từ chỉ mục 3 và kết thúc trước chỉ mục 6.
sub_arr2=np.split(arr,2) #chia mảng arr thành 2 phần bằng nhau
print("Mảng con sub_arr1 là:", sub_arr1, "\n")
print("Mảng con sub_arr2 là:", sub_arr2)

Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [14]:
import numpy as np
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
upper,lower = np.vsplit(arr,2) #Tách theo trục ngang
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(upper,"\n")
print(lower,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



In [16]:
left,right=np.hsplit(arr,2) #Tách theo trục dọc
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(left,"\n")
print(right,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

